### ISSUE TITLE
SumHeads bug

### ISSUE THREAD

**Issue by joshuaswickirl** [brodiep21/learnGoWithTests#1]
https://github.com/brodiep21/learnGoWithTests/blob/69515c042f59ecd54bd706fe16c8f1b3b59ebacc/internal/sum/sum_test.go#L43

The first slice is empty (len 0, cap 0), thus a slice of [:1] is referencing an index that is out of bound (does not exist).

**Comment by brodiep21** [comment]
fixed code issue in -- sum.go
```go
 for _, i := range variableSlices {
		if len(variableSlices) == 0 
```
changed to 
```go
	for _, i := range variableSlices {
		if len(i) == 0 
```
this resolves the issue of testing a slice with len 0
the code in the testing was correct!
